{
 "title": "server day",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "salon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active\") FROM \"cpu\" WHERE (\"host\" = 'salon' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "salon" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "mano",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active\") FROM \"cpu\" WHERE (\"host\" = 'mano' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "lifo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active\") FROM \"cpu\" WHERE (\"host\" = 'lifo' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "metal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active\") FROM \"cpu\" WHERE (\"host\" = 'metal' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "kubi0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active\") FROM \"cpu\" WHERE (\"host\" = 'kubi0' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "ryzen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active\") FROM \"cpu\" WHERE (\"host\" = 'ryzen' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    }
   ]
  },
  {
   "title": "ram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "salon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'salon') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "salon" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "mano",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'mano') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "lifo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'lifo') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "metal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'metal') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "kubi0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'kubi0') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "ryzen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'ryzen') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    }
   ]
  },
  {
   "title": "cpu temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "salon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"temp\") FROM \"temp\" WHERE (\"host\" = 'salon') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "salon" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "mano",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\")/1000 as value FROM \"cpu_temp\" WHERE (\"host\" = 'mano') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "lifo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\")/1000 as value FROM \"cpu_temp\" WHERE (\"host\" = 'lifo') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "metal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\")/1000 as value FROM \"cpu_temp\" WHERE (\"host\" = 'metal') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "kubi0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\")/1000 as value FROM \"cpu_temp\" WHERE (\"host\" = 'kubi0') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    }
   ]
  },
  {
   "title": "Ambient Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "servers box",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature\" FROM \"servers weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature\" FROM \"livingroom tag\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "PCs station",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT \"power\" FROM \"pc socket\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "salon" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "servers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT \"power\" FROM \"shelly routers servers\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "salon" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "salon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "query": "SELECT mean(\"query_time_ms\") FROM \"dns_query\" WHERE (\"host\" = 'salon') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "mano",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "query": "SELECT mean(\"query_time_ms\") FROM \"dns_query\" WHERE (\"host\" = 'mano') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lifo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "query": "SELECT mean(\"query_time_ms\") FROM \"dns_query\" WHERE (\"host\" = 'lifo') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "salon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'salon') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "salon" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "mano",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'mano') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "lifo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'lifo') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "metal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'metal') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "kubi0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'kubi0') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    },
    {
     "alias": "ryzen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'ryzen') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mano" }
     ]
    }
   ]
  }
 ]
}