esphome:
  name: nova-pm

#fail esp32-c3-devkitm-1 not fetching data from the sensor
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
uart:
  - id: sds011_uart
    tx_pin: 10
    rx_pin: 1
    baud_rate: 9600

mqtt:
  broker: 10.0.0.91
  discovery: false
  topic_prefix: esphome/nova-air/air

sensor:
  - platform: sds011
    uart_id: sds011_uart
    pm_2_5:
      name: "pm25"
      state_topic: esphome/nova-air/air/pm25
    pm_10_0:
      name: "pm10"
      state_topic: esphome/nova-air/air/pm10
    update_interval: 1min

logger:
  level: VERY_VERBOSE
  hardware_uart: UART0

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Env Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:
