esphome:
  name: nova-pm

esp32:
  board: esp32dev
  framework:
    type: arduino
uart:
  tx_pin: GPIO27
  rx_pin: GPIO26
  baud_rate: 9600

mqtt:
  broker: 10.0.0.91
  discovery: false
  topic_prefix: esphome/nova-air/air

sensor:
  - platform: sds011
    pm_2_5:
      name: "pm25"
      state_topic: esphome/nova-air/air/pm25
    pm_10_0:
      name: "pm10"
      state_topic: esphome/nova-air/air/pm10
    update_interval: 5min

#logger:
#  level: VERY_VERBOSE

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Env Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:
