version: "3.8"
services:
    zigAssistMano:
        image: carldebilly/zigbee2mqttassistant
        container_name: zigmano
        environment:
            - Z2MA_SETTINGS__MQTTSERVER=mano
            - Z2MA_SETTINGS__BASETOPIC=mzig
            - TZ=Europe/Berlin
        ports:
            - 8080:80
        restart: unless-stopped
    zigAssistLifo:
        image: carldebilly/zigbee2mqttassistant
        container_name: ziglifo
        environment:
            - Z2MA_SETTINGS__MQTTSERVER=mano
            - Z2MA_SETTINGS__BASETOPIC=lzig
            - TZ=Europe/Berlin
        ports:
            - 8090:80
        restart: unless-stopped
