version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "1884:1883"
    volumes:
      - ${PWD}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      restart: unless-stopped
  webapps:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/web/overview/public:/usr/share/nginx/html/home:ro
      - ${PWD}/zigbee/graph_view:/usr/share/nginx/html/zigbee:ro
      - ${PWD}/js/bed_heating:/usr/share/nginx/html/bed:ro
      - ${PWD}/js/heating:/usr/share/nginx/html/heat:ro
      - ${PWD}/js/leds_panel:/usr/share/nginx/html/leds:ro
      - ${PWD}/../smart_home_3d_webapp:/usr/share/nginx/html/3d:ro
      - ${PWD}/../nRF52_Mesh/nodes.json:/usr/share/nginx/html/nodes.json:ro
    network_mode: "host"
  zigAssMano:
      image: carldebilly/zigbee2mqttassistant
      environment:
          - Z2MA_SETTINGS__MQTTSERVER=10.0.0.42
          - Z2MA_SETTINGS__BASETOPIC=mzig
          - TZ=Europe/Berlin
      ports:
          - 8080:80
      restart: unless-stopped
  zigAssLifo:
      image: carldebilly/zigbee2mqttassistant
      environment:
          - Z2MA_SETTINGS__MQTTSERVER=10.0.0.42
          - Z2MA_SETTINGS__BASETOPIC=lzig
          - TZ=Europe/Berlin
      ports:
          - 8090:80
      restart: unless-stopped
  zigAssRifo:
      image: carldebilly/zigbee2mqttassistant
      environment:
          - Z2MA_SETTINGS__MQTTSERVER=10.0.0.42
          - Z2MA_SETTINGS__BASETOPIC=rzig
          - TZ=Europe/Berlin
      ports:
          - 8070:80
      restart: unless-stopped
