version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "1884:1883"
    volumes:
      - ${PWD}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  influx:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ${PWD}/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB:=mqtt
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    network_mode: "host"
    volumes:
      - ${PWD}/grafana/data:/var/lib/grafana
      - ${PWD}/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - "influx"
  nrf2mqtt:
    build:
      context: ./py/nrf_mesh
    network_mode: "host"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      - "webapps"
      - "mosquitto"
  mqtt2influx:
    build:
      context: ./py/influx
    network_mode: "host"
    depends_on:
      - "mosquitto"
      - "influx"
  webapps:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/zigbee/graph_view:/usr/share/nginx/html/zigbee:ro
      - ${PWD}/js/bed_heating:/usr/share/nginx/html/bed:ro
      - ${PWD}/js/heating:/usr/share/nginx/html/heat:ro
      - ${PWD}/js/leds_panel:/usr/share/nginx/html/leds:ro
      - ${PWD}/../smart_home_3d_webapp:/usr/share/nginx/html/3d:ro
      - ${PWD}/../nRF52_Mesh/nodes.json:/usr/share/nginx/html/nodes.json:ro
