version: "3.8"
services:
  mosquitto:
    #socket_domain ipv4 https://github.com/eclipse/mosquitto/issues/1004
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - ${PWD}/containers/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
  influx:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ${PWD}/containers/influxdb:/var/lib/influxdb
      - ${PWD}/containers/influxdb/data:/var/log/influx
    environment:
      - INFLUXDB_DB:=mqtt
  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    network_mode: "host"
    volumes:
      - ${PWD}/containers/grafana/data:/var/lib/grafana
      - ${PWD}/containers/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ${PWD}/containers/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - "influx"
    restart: always
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ${PWD}/containers/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Berlin
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    volumes:
      - ${PWD}/containers/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  nrf2mqtt:
    build:
      context: ./py/nrf_mesh
    network_mode: "host"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      - "webapps"
      - "mosquitto"
  mqtt2influx:
    build:
      context: ./py/influx
    network_mode: "host"
    depends_on:
      - "mosquitto"
      - "influx"
  udp2mqtt:
    build:
      context: ./py/thread_tags
    network_mode: "host"
    volumes:
      - ${PWD}/py/thread_tags/data:/var/log/thread
    depends_on:
      - "mosquitto"
  webapps:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/containers/nginx/404.html:/usr/share/nginx/html/404.html:ro
      - ${PWD}/containers/nginx/_next:/usr/share/nginx/html/_next:ro
      - ${PWD}/web/overview/public:/usr/share/nginx/html/home:ro
      - ${PWD}/web/heating:/usr/share/nginx/html/heat:ro
      - ${PWD}/web/home-next/out:/usr/share/nginx/html/next:ro
      - ${PWD}/../smart_home_3d_webapp:/usr/share/nginx/html/3d:ro
      - ${PWD}/../nRF52_Mesh/nodes.json:/usr/share/nginx/html/nodes.json:ro
    network_mode: "host"
    restart: always
  zigAssLifo:
      image: carldebilly/zigbee2mqttassistant
      environment:
          - Z2MA_SETTINGS__MQTTSERVER=10.0.0.31
          - Z2MA_SETTINGS__BASETOPIC=lzig
          - TZ=Europe/Berlin
      ports:
          - 8080:80
      restart: unless-stopped
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: always
    volumes:
      - ${PWD}/containers/conbee/data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
    ports:
      - "8000:80"
