version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - ${PWD}/containers/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
  influx:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - ${PWD}/containers/influxdb:/var/lib/influxdb
      - ${PWD}/py/influx/data:/var/log/influx
    environment:
      - INFLUXDB_DB:=mqtt
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    network_mode: "host"
    volumes:
      - ${PWD}/containers/grafana/data:/var/lib/grafana
      - ${PWD}/containers/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ${PWD}/containers/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - "influx"
    restart: unless-stopped
