esphome:
  name: bedroom-env

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
i2c:
  scl: 10
  sda: 1
  scan: true

mqtt:
  broker: 10.0.0.91
  discovery: false
  topic_prefix: esphome/bedroom env

sensor:
  - platform: sgp30
    eco2:
      name: "Equivalent CO2"
      accuracy_decimals: 1
    tvoc:
      name: "Total Volatile Organic Compounds"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 10s

ota:
  password: ""

wifi:
  ssid: "TW24"
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Env Fallback Hotspot"
    password: ""

captive_portal:
