# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors/
cover:
  - platform: "mqtt"
    name: "Bedroom window roll"
    availability_topic: "lzig/bridge/state"
    command_topic: "lzig/bedroom roll/set"
    position_template: "{{ value_json.position }}"
    set_position_template: "{ \"position\": {{ position }} }"
    set_position_topic: "lzig/bedroom roll/set"
    position_topic: "lzig/bedroom roll"
