#!/bin/bash
influx -execute 'SELECT * INTO mqtt.."Balcony tag" FROM nrf_mesh.."Balcony tag"'
influx -execute 'SELECT * INTO mqtt.."Bathroom tag" FROM nrf_mesh.."Bathroom tag"'
influx -execute 'SELECT * INTO mqtt.."Bedroom tag" FROM nrf_mesh.."Bedroom tag"'
influx -execute 'SELECT * INTO mqtt.."Flora1Hallway tag" FROM nrf_mesh.."Flora1Hallway tag"'
influx -execute 'SELECT * INTO mqtt.."Kitchen tag" FROM nrf_mesh.."Kitchen tag"'
influx -execute 'SELECT * INTO mqtt.."Livingroom tag" FROM nrf_mesh.."Livingroom tag"'
influx -execute 'SELECT * INTO mqtt.."Livingroom window tag" FROM nrf_mesh.."Livingroom window tag"'
influx -execute 'SELECT * INTO mqtt.."Office tag" FROM nrf_mesh.."Office tag"'
influx -execute 'SELECT * INTO mqtt.."balcony weather" FROM nrf_mesh.."balcony weather"'
influx -execute 'SELECT * INTO mqtt.."fridge weather" FROM nrf_mesh.."fridge weather"'
influx -execute 'SELECT * INTO mqtt.."bathroom heat" FROM nrf_mesh.."bathroom heat"'
influx -execute 'SELECT * INTO mqtt.."bed weather" FROM nrf_mesh.."bed weather"'
influx -execute 'SELECT * INTO mqtt.."bedroom heat" FROM nrf_mesh.."bedroom heat"'
influx -execute 'SELECT * INTO mqtt.."kitchen heat" FROM nrf_mesh.."kitchen heat"'
influx -execute 'SELECT * INTO mqtt.."living heat" FROM nrf_mesh.."living heat"'
influx -execute 'SELECT * INTO mqtt.."office heat" FROM nrf_mesh.."office heat"'
influx -execute 'SELECT * INTO mqtt.."office weather" FROM nrf_mesh.."office weather"'

influx -execute 'SELECT * INTO test.."kitchen tag" FROM mqtt.."kitchen tag"'
