esphome:
  name: pms5003t

esp32:
  board: esp32dev
  framework:
    type: arduino
uart:
  tx_pin: GPIO17
  rx_pin: GPIO21
  baud_rate: 9600

mqtt:
  broker: 10.0.0.91
  discovery: false
  topic_prefix: esphome/pms5003t/air

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: pm1
      state_topic: esphome/pms5003t/air/pm1
    pm_2_5:
      name: pm25
      state_topic: esphome/pms5003t/air/pm25
    pm_10_0:
      name: pm10
      state_topic: esphome/pms5003t/air/pm10
    temperature:
      name: temperature
      state_topic: esphome/pms5003t/env/temperature
    humidity:
      name: humidity
      state_topic: esphome/pms5003t/env/humidity
    update_interval: 5min

#logger:
#  level: VERY_VERBOSE

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Env Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:
