version: "2"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: always
    volumes:
      - ${PWD}/data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
    ports:
      - "8000:80"
